// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64
	Name      string
	SectionID pgtype.Int8
}

type Menu struct {
	ID        int64
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type MenusCategory struct {
	ID         int64
	MenuID     int64
	CategoryID int64
	Sort       int32
}

type Product struct {
	ID         int64
	Name       string
	Abbr       string
	Price      pgtype.Numeric
	CategoryID pgtype.Int8
}

type ProductsVariant struct {
	ProductID int64
	VariantID int64
}

type Section struct {
	ID   int64
	Name string
}

type User struct {
	ID       int64
	Email    string
	Password string
	Salt     string
}

type Variant struct {
	ID    int64
	Name  string
	Price pgtype.Numeric
}
