services:
  build-image:
    container_name: build-image 
    build:
      context: ./
      dockerfile: _docker/go/arm.Dockerfile
      target: prod
      tags:
        - "sagre:build"
    environment:
      ENV: ${ENV}
      DB_URL: ${DB_URL}
      STORE_KEY: ${STORE_KEY}
      PORT: ${PORT}
      ADDRESS: ${ADDRESS}
    exclude_from_hc: true
   
  sagre-migration: 
    container_name: sagre-migration 
    image: "sagre:build"
    extends:
      service: build-image
    depends_on: 
      - build-image
      - db
    entrypoint: /src/app/sql-migrate
    command: ["up", "-config=config/dbconfig.yml"]
    exclude_from_hc: true

  sagre:
    container_name: api
    extends:
      service: build-image
    image: sagre:build 
    restart: always
    depends_on: 
      - build-image
      - sagre-migration
    entrypoint: /src/app/bin/main

  db:
    container_name: ${SERVICE_BASE64_DB_NAME}
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: sagre
      POSTGRES_PASSWORD: sagre
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./postgres/docker-entrypoint-initdb/:/docker-entrypoint-initdb.d/
      - ./postgres/data:/var/lib/postgresql/data
    exclude_from_hc: true
