services:
  build-image:
    build:
      context: ./
      dockerfile: _docker/go/arm.Dockerfile
      target: prod
      tags:
        - "sagre:build"
    restart: "no"
    environment:
      ENV: ${ENV}
      DB_URL: ${DB_URL}
      STORE_KEY: ${STORE_KEY}
      PORT: ${PORT}
      ADDRESS: ${ADDRESS}
   
  sagre-migration: 
    image: "sagre:build"
    restart: "no"
    extends:
      service: build-image
    depends_on: 
      db:
        condition: service_healthy
      build-image:
        condition: service_completed_successfully
    entrypoint: /src/app/sql-migrate
    command: ["up", "-config=config/dbconfig.yml"]

  sagre:
    container_name: api
    extends:
      service: build-image
    image: sagre:build 
    restart: always
    depends_on: 
      build-image:
        condition: service_started
      sagre-migration:
        condition: service_completed_successfully
    entrypoint: /src/app/bin/main

  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: sagre
      POSTGRES_PASSWORD: sagre
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - type: bind
        source: ./srv/create.sql
        target: /docker-entrypoint-initdb.d/create.sql
        content: |
           CREATE DATABASE sagre_go OWNER sagre;
      - type: bind
        source: ./srv/extension.sql
        target: /docker-entrypoint-initdb.d/extension.sql
        content: |
           \c sagre_go
            CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
      - ./postgres/data:/var/lib/postgresql/data
